//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revenda
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasesView
    {
        public int Pedido { get; set; }
        public int Item { get; set; }
        public System.DateTime Data { get; set; }
        public string CondPagto { get; set; }
        public int CodProduto { get; set; }
        public string Descrição { get; set; }
        public decimal CustoU { get; set; }
        public decimal Qtde { get; set; }
    }
}
